### ISSUE TITLE
Error 500 when calling /tasks/iocs/<task_id>

### ISSUE THREAD

**Issue by jbickfrd** [ctxis/CAPE#287]
While querying calling the /tasks/iocs/<task_id> API endpoint  we are getting an Error 500. When looking at the logs the python traceback shows createProcessTreeNode function is not defined.

```Feb 20 18:10:08 python: Traceback (most recent call last):
Feb 20 18:10:08 python: File "/home/cuckoo/cape_venv/lib/python2.7/site-packages/bottle.py", line 862, in _handle
Feb 20 18:10:08 python: return route.call(**args)
Feb 20 18:10:08 python: File "/home/cuckoo/cape_venv/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
Feb 20 18:10:08 python: rv = callback(*a, **ka)
Feb 20 18:10:08 python: File "/data/cuckoo/CAPE/utils/api.py", line 517, in tasks_iocs
Feb 20 18:10:08 python: "spawned_processes": [createProcessTreeNode(child_process) for child_process in buf["behavior"]["processtree"][0]["children"]]
Feb 20 18:10:08 python: NameError: global name 'createProcessTreeNode' is not defined
Feb 20 18:10:08 python: 10.44.2.3 - - [20/Feb/2019 18:10:08] "GET /tasks/iocs/62 HTTP/1.1" 500 754```

**Comment by doomedraven** [comment]
try this https://github.com/ctxis/CAPE/pull/289

**Comment by doomedraven** [comment]
you are welcome :)
