### ISSUE TITLE
alembic upgrade head

### ISSUE THREAD

**Issue by DefenderLab** [ctxis/CAPE#292]
Unable to go ahead after below step

INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.

**Comment by doomedraven** [comment]
Why do you exec it? We didnt change db

**Comment by DefenderLab** [comment]
Thanks for the reply.

I am following steps mention in below doc:

CAPE/docs/book/src/installation/upgrade.rst

Please correct me if I am going wrong.  If you have any video for installation, please share it.

**Comment by doomedraven** [comment]
videos sucks, wasting of time :P
upgrade -> `git pull`, thats all :) alembic is for db upgrade, and there is no db upgrade in years

**Comment by kevoreilly** [comment]
Maybe we should ditch those docs?

**Comment by doomedraven** [comment]
nah, just add specification of alembic

**Comment by DefenderLab** [comment]
Sorry I didn't get above steps. 
I have already installed cuckoo after that I and trying to install CAPE.  Can anyone share easy steps for CAPE installation?

**Comment by doomedraven** [comment]
you are so wrong...
cuckoo or cape, cape isn't extension of cuckoo v2, that is fork

see https://github.com/doomedraven/Tools/blob/master/Cuckoo/cuckoo.sh

**Comment by doomedraven** [comment]
sudo ./cuckoo.sh all cape IP # in case if you using tor

**Comment by DefenderLab** [comment]
Thanks  Doomedraven,

I have successfully installed the above shell script, after installation found error no no crontab set, please help me on this.

**Comment by doomedraven** [comment]
without log of error can't help

**Comment by DefenderLab** [comment]
Hi,

following are some last recent logs:

Running setup.py install for django-ratelimit ... done
Running setup.py install for pydeep ... done
Successfully installed altgraph-0.16.1 decorator-4.3.2 dis3-0.1.3 django-ratelimit-3.0a0 elasticsearch-6.3.1 graphviz-0.10.1 java-random-1.0 macholib-1.11 mixbox-1.0.3 networkx-2.2 olefile-0.45.1 ordered-set-3.1 pydeep-0.4 pydot-1.4.1 pyelftools-0.25 pyinstaller-3.4 python-whois-0.7.1 pyyaml-3.13 regex-2019.2.21 weakrefmethod-1.0.3 xmltodict-0.12.0
Failed to enable unit: Unit file supervisord.service does not exist.
Failed to start supervisord.service: Unit supervisord.service not found.
Restarted supervisord
No config updates to processes
no crontab for root

What is the next step to do for me?

**Comment by doomedraven** [comment]
as it says you don't have supervisor for some reason, but it is in script so you need to check why you don't have it

**Comment by DefenderLab** [comment]
Thank you for your reply,
I started service of supervisor using "sudo systemctl start supervisor" and now its running successfully.
but what's about crontab and "No config updates to processes".

**Comment by doomedraven** [comment]
for crontab you can see crontabs in script and execute the by hand, about `"No config updates to processes".` not sure from where it comes

**Comment by DefenderLab** [comment]
Okay thank you,
I have sets all crontabs now.
May I know what is next step to do now.

**Comment by doomedraven** [comment]
the step is enjoy :)

**Comment by doomedraven** [comment]
after configure all config files

**Comment by DefenderLab** [comment]
Yes, I configured all required settings, but for cuckoo we run command "cuckoo -d" and "cuckoo web" but for CAPE what are the commands.

**Comment by doomedraven** [comment]
python cuckoo.py -d 
from web folder
python manage runserver 0.0.0.0:8000

**Comment by DefenderLab** [comment]
Thanks for the inputs, 
now server is started successfully but I facing issue while running: "python manage runserver 0.0.0.0:8000"
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7fe2032fce60>
Traceback (most recent call last):
  File "/home/admin1/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/admin1/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/home/admin1/.local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/admin1/.local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/admin1/.local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/admin1/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/admin1/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/admin1/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/home/admin1/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/admin1/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/admin1/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/admin1/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/CAPE/web/web/urls.py", line 15, in <module>
    from submission import urls as submission
  File "/opt/CAPE/web/submission/urls.py", line 6, in <module>
    from submission import views
  File "/opt/CAPE/web/submission/views.py", line 83, in <module>
    session = create_session(repconf.distributed.db)
  File "/opt/CAPE/web/../lib/cuckoo/common/dist_db.py", line 95, in create_session
    engine = create_engine(db_connectionn, pool_size=20, max_overflow=100)
  File "/home/admin1/.local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 431, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/admin1/.local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 172, in create
    engineclass.__name__,
TypeError: Invalid argument(s) 'pool_size','max_overflow' sent to create_engine(), using configuration SQLiteDialect_pysqlite/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.

**Comment by DefenderLab** [comment]
After patching using temp fix [#299](https://github.com/ctxis/CAPE/pull/299/commits/d9ec319fbb4b3b992350fb65f95dbd4fc8b0d785)

I'm facing following issue:
Performing system checks...

System check identified no issues (0 silenced).
February 25, 2019 - 06:09:16
Django version 1.11.20, using settings 'web.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function wrapper at 0x7f542f82ae60>
Traceback (most recent call last):
  File "/home/admin1/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/admin1/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 146, in inner_run
    handler = self.get_handler(*args, **options)
  File "/home/admin1/.local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 28, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "/home/admin1/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 67, in get_handler
    return get_internal_wsgi_application()
  File "/home/admin1/.local/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 47, in get_internal_wsgi_application
    return import_string(app_path)
  File "/home/admin1/.local/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/CAPE/web/web/wsgi.py", line 89, in <module>
    application = get_wsgi_application()
  File "/home/admin1/.local/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/home/admin1/.local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 151, in __init__
    self.load_middleware()
  File "/home/admin1/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 58, in load_middleware
    mw_instance = mw_class()
TypeError: __init__() takes exactly 2 arguments (1 given)
