### ISSUE TITLE
django web UI broken with postgresql

### ISSUE THREAD

**Issue by seanthegeek** [ctxis/CAPE#298]
cc @kevoreilly 

@doomedraven's distributed changes a few commits back causes this error

python manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7fc63c059050>
Traceback (most recent call last):
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 124, in inner_run
    self.check(display_num_errors=True)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/cuckoo/CAPE/web/web/urls.py", line 15, in <module>
    from submission import urls as submission
  File "/home/cuckoo/CAPE/web/submission/urls.py", line 6, in <module>
    from submission import views
  File "/home/cuckoo/CAPE/web/submission/views.py", line 83, in <module>
    session = create_session(repconf.distributed.db)
  File "/home/cuckoo/CAPE/web/../lib/cuckoo/common/dist_db.py", line 95, in create_session
    engine = create_engine(db_connectionn, pool_size=20, max_overflow=100)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 425, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/cuckoo/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 162, in create
    engineclass.__name__))
TypeError: Invalid argument(s) 'pool_size','max_overflow' sent to create_engine(), using configuration SQLiteDialect_pysqlite/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.

**Comment by doomedraven** [comment]
hm im not sure how it possible

```
if HAVE_DIST:
    session = create_session(repconf.distributed.db)
```

temp fix
https://github.com/ctxis/CAPE/pull/299

don't close it i will need to investigate when i will have some time, but no time at the moment, it works fine on my side with psql

**Comment by DigiAngel** [comment]
Seeing the same as of today.

**Comment by doomedraven** [comment]
Check last pr there is a temp fix, i need all versions of all as herr with
psql 10 and flask-sqlalchemy works fine

**Comment by DigiAngel** [comment]
Thanks...temp fix worked like a champ...I should have included that in my response :)

**Comment by DigiAngel** [comment]
Of interest, I don't have postgresql installed...so that's a thing.

**Comment by doomedraven** [comment]
Once i will be back in 10d i will invistigate that

**Comment by DigiAngel** [comment]
Enjoy and be safe :)

**Comment by DefenderLab** [comment]
Hi,
After patching I'm also facing new issue:
sudo python manage.py runserver 0.0.0.0:8000
Performing system checks...

System check identified no issues (0 silenced).
February 25, 2019 - 06:13:37
Django version 1.11.20, using settings 'web.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function wrapper at 0x7ff5fdcd2e60>
Traceback (most recent call last):
  File "/home/admin1/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/admin1/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 146, in inner_run
    handler = self.get_handler(*args, **options)
  File "/home/admin1/.local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 28, in get_handler
    handler = super(Command, self).get_handler(*args, **options)
  File "/home/admin1/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 67, in get_handler
    return get_internal_wsgi_application()
  File "/home/admin1/.local/lib/python2.7/site-packages/django/core/servers/basehttp.py", line 47, in get_internal_wsgi_application
    return import_string(app_path)
  File "/home/admin1/.local/lib/python2.7/site-packages/django/utils/module_loading.py", line 20, in import_string
    module = import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/CAPE/web/web/wsgi.py", line 89, in <module>
    application = get_wsgi_application()
  File "/home/admin1/.local/lib/python2.7/site-packages/django/core/wsgi.py", line 14, in get_wsgi_application
    return WSGIHandler()
  File "/home/admin1/.local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 151, in __init__
    self.load_middleware()
  File "/home/admin1/.local/lib/python2.7/site-packages/django/core/handlers/base.py", line 58, in load_middleware
    mw_instance = mw_class()
TypeError: __init__() takes exactly 2 arguments (1 given)

**Comment by seanthegeek** [comment]
That fixed in this commit. https://github.com/ctxis/CAPE/commit/166d912c1d78ce7a55c8f17346976cc28896f74e

To apply the fix, run

pip install -U django-ratelimit==2.0.0

**Comment by seanthegeek** [comment]
@doomedraven Thanks for the workaround. For reference, I am using SQLAlchemy 1.2.18 and PostgreSQL 10.6 on Ubuntu 18.04.2 LTS.

I don`t have `flask-sqlalchemy` installed. Is that a requirement?

**Comment by DefenderLab** [comment]
Thanks for your reply,
It's working properly,
but in server side, I'm facing new issue as:

CAPE: Config and Payload Extraction
github.com/ctxis/CAPE

2019-03-01 09:24:53,167 [root] INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
2019-03-01 09:24:53,192 [root] INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
2019-03-01 09:24:55,267 [root] INFO: Updated running task ID 5 status to failed_analysis
2019-03-01 09:24:55,276 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" machine manager with max_analysis_count=0, max_machines_count=2, and max_vmstartup_count=2
2019-03-01 09:24:55,669 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2019-03-01 09:24:55,677 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2019-03-01 09:25:01,882 [lib.cuckoo.core.scheduler] INFO: Task #6: Starting analysis of FILE '/tmp/cuckoo-tmp/upload_Yij1WC/iwamregutilman.exe'
2019-03-01 09:25:01,891 [lib.cuckoo.core.scheduler] INFO: Task #6: File already exists at '/opt/CAPE/storage/binaries/4a1af05a3afda885bc4ee6ee68d642ce5cb312ad282869c473ca5d543e41db19'
2019-03-01 09:25:01,958 [lib.cuckoo.core.scheduler] INFO: Task #6: acquired machine cuckoo1 (label=cuckoo1)
2019-03-01 09:25:05,299 [lib.cuckoo.core.rooter] CRITICAL: Unable to passthrough root command as we're unable to connect to the rooter unix socket: [Errno 13] Permission denied.
2019-03-01 09:25:05,301 [lib.cuckoo.core.scheduler] INFO: Enabled route 'none'
2019-03-01 09:25:05,318 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 2154 (interface=vboxnet0, host=192.168.56.101, dump path=/opt/CAPE/storage/analyses/6/dump.pcap)
2019-03-01 09:25:05,384 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=cuckoo1, ip=192.168.56.101)
2019-03-01 09:29:42,830 [lib.cuckoo.core.scheduler] ERROR: The analysis hit the critical timeout, terminating.
 
Can you help me.

**Comment by kevoreilly** [comment]
Hmm I think the rooter needs to run with root privileges... Something like sudo python rooter.py -v -g cuckoo. Let me know how it goes.

**Comment by DefenderLab** [comment]
Thanks for reply,
I tried this but it still gave same error.

**Comment by doomedraven** [comment]
Show socket file permission(path in cuckoo.conf)

**Comment by DefenderLab** [comment]
Hi,

Following are socket file permissions:
srwxrwxrwx 1 root   root       0 Mar  4 06:31 cuckoo-rooter

**Comment by doomedraven** [comment]
and how you executed it? all your stuff is running under cuckoo?

**Comment by DefenderLab** [comment]
Hi,
cuckoo-rooter file is of 0 bytes.
I'm running all things using normal user as following commands,
python cuckoo.py
python manage.py runserver 0.0.0:8000

**Comment by doomedraven** [comment]
im asking about user under which that all started?

**Comment by DefenderLab** [comment]
admin1@admin-ThinkCentre-Edge72:/opt/CAPE/web$ python manage.py runserver 0.0.0.0:8000
admin1@admin-ThinkCentre-Edge72:/opt/CAPE$ python cuckoo.py

**Comment by DefenderLab** [comment]
It's not cuckoo user. It is different user.

**Comment by doomedraven** [comment]
that is what i told, everything should be started under cuckoo user, not admin1 or others `sudo python rooter.py -v -g admin1` you should use --help for all the stuff you use to avoid this

**Comment by DefenderLab** [comment]
Yeah, Thanks a lot, that error is gone now :)

**Comment by doomedraven** [comment]
since now start using `--help` please, is there for help

**Comment by DefenderLab** [comment]
Yes, Thanks for support.

Now I'm getting below issue.
2019-03-04 09:44:58,350 [lib.cuckoo.core.scheduler] ERROR: The analysis hit the critical timeout, terminating.
2019-03-04 09:45:04,596 [lib.cuckoo.common.objects] WARNING: failed to scan file with clamav Error 2 connecting /var/run/clamav/clamd.ctl. No such file or directory.
2019-03-04 09:45:04,606 [lib.cuckoo.common.objects] WARNING: failed to scan file with clamav Error 2 connecting /var/run/clamav/clamd.ctl. No such file or directory.
2019-03-04 09:45:04,630 [lib.cuckoo.common.objects] WARNING: failed to scan file with clamav Error 2 connecting /var/run/clamav/clamd.ctl. No such file or directory.
2019-03-04 09:45:04,646 [lib.cuckoo.common.objects] WARNING: failed to scan file with clamav Error 2 connecting /var/run/clamav/clamd.ctl. No such file or directory.
2019-03-04 09:45:04,655 [lib.cuckoo.common.objects] WARNING: failed to scan file with clamav Error 2 connecting /var/run/clamav/clamd.ctl. No such file or directory.
2019-03-04 09:45:04,671 [lib.cuckoo.common.objects] WARNING: failed to scan file with clamav Error 2 connecting /var/run/clamav/clamd.ctl. No such file or directory.
2019-03-04 09:45:04,686 [lib.cuckoo.common.objects] WARNING: failed to scan file with clamav Error 2 connecting /var/run/clamav/clamd.ctl. No such file or directory.
2019-03-04 09:45:04,703 [lib.cuckoo.common.objects] WARNING: failed to scan file with clamav Error 2 connecting /var/run/clamav/clamd.ctl. No such file or directory.
2019-03-04 09:45:04,715 [lib.cuckoo.common.objects] WARNING: failed to scan file with clamav Error 2 connecting /var/run/clamav/clamd.ctl. No such file or directory.
2019-03-04 09:45:04,771 [lib.cuckoo.common.objects] WARNING: failed to scan file with clamav Error 2 connecting /var/run/clamav/clamd.ctl. No such file or directory.
2019-03-04 09:45:04,784 [lib.cuckoo.common.objects] WARNING: failed to scan file with clamav Error 2 connecting /var/run/clamav/clamd.ctl. No such file or directory.
2019-03-04 09:45:08,415 [lib.cuckoo.common.objects] WARNING: failed to scan file with clamav Error 2 connecting /var/run/clamav/clamd.ctl. No such file or directory.
2019-03-04 09:45:08,429 [lib.cuckoo.common.objects] WARNING: failed to scan file with clamav Error 2 connecting /var/run/clamav/clamd.ctl. No such file or directory.
2019-03-04 09:45:08,486 [lib.cuckoo.common.objects] WARNING: failed to scan file with clamav Error 2 connecting /var/run/clamav/clamd.ctl. No such file or directory.
2019-03-04 09:45:08,918 [lib.cuckoo.common.objects] WARNING: failed to scan file with clamav Error 2 connecting /var/run/clamav/clamd.ctl. No such file or directory.

**Comment by doomedraven** [comment]
dude start searching in issues, that isn't an error, just time for sample is out to be analyzed in vm, and about clamad, sound like you have python binding but not clamav itself, anyway isn't very useful

**Comment by DefenderLab** [comment]
But, I unable to see any report on UI,

Environment:


Request Method: GET
Request URL: http://0.0.0.0:8000/analysis/16/

Django Version: 1.11.5
Python Version: 2.7.15
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'analysis',
 'compare',
 'api',
 'ratelimit')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'web.headers.CuckooHeaders',
 'ratelimit.middleware.RatelimitMiddleware')



Traceback:

File "/home/admin1/.local/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/home/admin1/.local/lib/python2.7/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/home/admin1/.local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/home/admin1/.local/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/admin1/.local/lib/python2.7/site-packages/django/views/decorators/http.py" in inner
  40.             return func(request, *args, **kwargs)

File "/opt/CAPE/web/analysis/views.py" in report
  737.                      sort=[("_id", pymongo.DESCENDING)]

File "/home/admin1/.local/lib/python2.7/site-packages/pymongo/collection.py" in find_one
  1262.         for result in cursor.limit(-1):

File "/home/admin1/.local/lib/python2.7/site-packages/pymongo/cursor.py" in next
  1189.         if len(self.__data) or self._refresh():

File "/home/admin1/.local/lib/python2.7/site-packages/pymongo/cursor.py" in _refresh
  1087.             self.__session = self.__collection.database.client._ensure_session()

File "/home/admin1/.local/lib/python2.7/site-packages/pymongo/mongo_client.py" in _ensure_session
  1563.             return self.__start_session(True, causal_consistency=False)

File "/home/admin1/.local/lib/python2.7/site-packages/pymongo/mongo_client.py" in __start_session
  1516.         server_session = self._get_server_session()

File "/home/admin1/.local/lib/python2.7/site-packages/pymongo/mongo_client.py" in _get_server_session
  1549.         return self._topology.get_server_session()

File "/home/admin1/.local/lib/python2.7/site-packages/pymongo/topology.py" in get_server_session
  427.                             None)

File "/home/admin1/.local/lib/python2.7/site-packages/pymongo/topology.py" in _select_servers_loop
  199.                     self._error_message(selector))

Exception Type: ServerSelectionTimeoutError at /analysis/16/
Exception Value: 127.0.0.1:27017: [Errno 111] Connection refused

**Comment by doomedraven** [comment]
your mongo not running that all

**Comment by doomedraven** [comment]
i have a tip for you, google is a good solution :)
and the best way to deploy all the stuff https://github.com/doomedraven/Tools/blob/master/Cuckoo/cuckoo.sh

**Comment by DefenderLab** [comment]
Thanks,
I installed CAPE by using this: https://github.com/doomedraven/Tools/blob/master/Cuckoo/cuckoo.sh

but still I gets errors.  :(

And still it showing on UI: Error: The analysis hit the critical timeout, terminating.

**Comment by doomedraven** [comment]
dude as i told you `And still it showing on UI: Error: The analysis hit the critical timeout, terminating.`

```
dude start searching in issues, that isn't an error, just time for sample is out to be analyzed in vm,
```

well you used script but you not followed stuff in there
1. how you executed it?
2. why not cuckoo and admin1
3. which os?

that script is for ubuntu 18.04 lts which leaves perfeclly usable CAPE/v2 setup, a lot of friends used that, so you just didn't hollow something or didn't check output if something failed

**Comment by DefenderLab** [comment]
Everything is working fine, thank you for your support.

**Comment by kevoreilly** [comment]
Thanks all for sorting this!
