### ISSUE TITLE
ERROR: Failed to run the processing module "Dropped":

### ISSUE THREAD

**Issue by YESIHACK** [ctxis/CAPE#381]
Hi I'm having an issue with CAPE connecting to my guest VM. I have verified that networking is not the issue and am able to curl vmip:8000 and get code 501. I continually get  

2019-08-09 10:34:46,303 [lib.cuckoo.core.guest] DEBUG: Win7: not ready yet
2019-08-09 10:34:47,305 [lib.cuckoo.core.guest] DEBUG: Win7: not ready yet
2019-08-09 10:34:48,306 [lib.cuckoo.core.guest] DEBUG: Win7: not ready yet
2019-08-09 10:34:49,307 [lib.cuckoo.core.guest] DEBUG: Win7: not ready yet
2019-08-09 10:34:50,309 [lib.cuckoo.core.guest] DEBUG: Win7: not ready yet
2019-08-09 10:34:51,311 [lib.cuckoo.core.guest] DEBUG: Win7: not ready yet
2019-08-09 10:34:52,313 [lib.cuckoo.core.guest] DEBUG: Win7: not ready yet
2019-08-09 10:34:53,314 [lib.cuckoo.core.guest] DEBUG: Win7: not ready yet

and no activity on my VM. After timeout I get the following error

2019-08-09 10:35:02,698 [lib.cuckoo.core.plugins] ERROR: Failed to run the processing module "Dropped":
Traceback (most recent call last):
  File "/home/cuckoo/CAPE/lib/cuckoo/core/plugins.py", line 197, in process
    data = current.run()
  File "/home/cuckoo/CAPE/modules/processing/dropped.py", line 28, in run
    file_names = os.listdir(self.dropped_path)
OSError: [Errno 2] No such file or directory: '/opt/CAPE/storage/analyses/6/files'

After going to the dir I noticed the "files" dir doesn't exists. Any tips for resolving this issue.

**Comment by doomedraven** [comment]
yes that isn't really failing, that just need a better check if folder exist, nothing else

**Comment by YESIHACK** [comment]
how does this folder get created? Also how does CAPE connect to guest vm. tried looking for traffic with wireshark but can't find packets that reach out to guest vm.

**Comment by doomedraven** [comment]
it connect to agent, agent listen on vm on port 8000, and host listen on port 2042

are you able to do this once vm started

`curl vm_info:8000` that should give you error 50x is you get that that means all works as expected, can you verify that?

**Comment by YESIHACK** [comment]
This is what I get when I curl the guest VM that is running the agent.

cuckoo@ubuntu:/opt$ curl 192.168.100.101:8000
<head>
<title>Error response</title>
</head>
<body>
<h1>Error response</h1>
<p>Error code 501.
<p>Message: Unsupported method ('GET').
<p>Error code explanation: 501 = Server does not support this operation.
</body>

also CAPE has something listening on 2042

root@ubuntu:/opt# netstat -tulp |grep 2042
tcp        0      0 ubuntu:2042             0.0.0.0:*               LISTEN      9637/python    

Both the VM and host can ping each other. FireWall is off on guest VM.

root@ubuntu:/opt# ping 192.168.100.101
PING 192.168.100.101 (192.168.100.101) 56(84) bytes of data.
64 bytes from 192.168.100.101: icmp_seq=1 ttl=128 time=0.520 ms
64 bytes from 192.168.100.101: icmp_seq=2 ttl=128 time=0.404 ms
64 bytes from 192.168.100.101: icmp_seq=3 ttl=128 time=0.541 ms
64 bytes from 192.168.100.101: icmp_seq=4 ttl=128 time=0.503 ms
64 bytes from 192.168.100.101: icmp_seq=5 ttl=128 time=0.404 ms

**Comment by doomedraven** [comment]
well it looks like everything works, maybe you have something wrong in cuckoo.conf or your hypervisor not sure whihc one do you use

**Comment by YESIHACK** [comment]
I use KVM. Here is the Conf.

[kvm]
# Specify a comma-separated list of available machines to be used. For each
# specified ID you have to define a dedicated section containing the details
# on the respective machine. (E.g. cuckoo1,cuckoo2,cuckoo3)
machines = Win7

interface=virbr1

[Win7]
# Specify the label name of the current machine as specified in your
# libvirt configuration.
label = Win7

# Specify the operating system platform used by current machine
# [windows/darwin/linux].
platform = windows

# Specify the IP address of the current virtual machine. Make sure that the
# IP address is valid and that the host machine is able to reach it. If not,
# the analysis will fail. You may want to configure your network settings in
# /etc/libvirt/<hypervisor>/networks/
ip=192.168.100.101

# (Optional) Specify the snapshot name to use. If you do not specify a snapshot
# name, the KVM MachineManager will use the current snapshot.
# Example (Snapshot1 is the snapshot name):
 snapshot=Win7Snapshot

# (Optional) Specify the name of the network interface that should be used
# when dumping network traffic from this machine with tcpdump. If specified,
# overrides the default interface specified in auxiliary.conf
# Example (virbr0 is the interface name):
interface=virbr1

# (Optional) Specify the IP of the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the IP address for the Result Server as your machine sees it. If you don't specify an
# address here, the machine will use the default value from cuckoo.conf.
# NOTE: if you set this option you have to set result server IP to 0.0.0.0 in cuckoo.conf.
# Example:
resultserver_ip = 192.168.100.101

# (Optional) Specify the port for the Result Server, as your virtual machine sees it.
# The Result Server will always bind to the address and port specified in cuckoo.conf,
# however you could set up your virtual network to use NAT/PAT, so you can specify here
# the port for the Result Server as your machine sees it. If you don't specify a port
# here, the machine will use the default value from cuckoo.conf.
# Example:
 resultserver_port = 2042

# (Optional) Set your own tags. These are comma separated and help to identify
# specific VMs. You can run samples on VMs with tag you require.
# Note that the 64_bit tag is currently special.  For submitted 64-bit PE files,
# the 64_bit tag will automatically be added, forcing them to be run on a 64-bit
# VM.  For this reason, make sure all 64-bit VMs have the 64_bit tag.
# tags = windows_xp_sp3,32_bit,acrobat_reader_6

# (Optional) Specify a memory profile to be used by volatility for this
# virtual machine. This will override the guest_profile variable in
# memory.conf which solves the problem of having multiple types of VM's
# and properly determining which profile to use. Examples below:
#mem_profile = WinXPSP2x86
#mem_profile = Win7SP0x86
#mem_profile = Win7SP1x64

**Comment by doomedraven** [comment]
ok make sure that in cuckoo.conf the result server is 192.168.100.1 and machinery is kvm

**Comment by doomedraven** [comment]
i hope you used this https://github.com/doomedraven/Tools/blob/master/Virtualization/kvm-qemu.sh

**Comment by YESIHACK** [comment]
Machinery is KVM and CAPE is able to load the virtual machine and start from the snapshot. I am not using the script you shared I manually installed from an old tutorial related to Cuckoo. I KVM is working fine
![Capture](https://user-images.githubusercontent.com/10007104/62778445-697dab80-ba7e-11e9-8dd7-ab4c67b373d8.PNG)
![Capture1](https://user-images.githubusercontent.com/10007104/62778446-697dab80-ba7e-11e9-8f74-c1b165d557b3.PNG)


 as seen in the photo attached.

**Comment by doomedraven** [comment]
that is not enough log for second one, so provide full log

+if you installed kvm from using apt then test it with vm detection and it will be catched https://github.com/LordNoteworthy/al-khaser

**Comment by YESIHACK** [comment]
Thanks for that test. I am a student setting this up as a lab project. I was looking into vm detection scripts.

Here is full log.
https://gist.github.com/YESIHACK/10fb67add91840f28fa672e196d76e66

**Comment by doomedraven** [comment]
You have some problem asyou can see guest initialization is timeout

**Comment by YESIHACK** [comment]
I am able to Curl the virtual machine the virtual machine and shown above and ping reach the vm from the host machine. Not sure what causing this issue to occur.

**Comment by doomedraven** [comment]
Check the cuckoo.conf

**Comment by YESIHACK** [comment]
Here is the log don't see anything not normal
Cuckoo conf log
https://gist.github.com/YESIHACK/53bb0bc7d83783a38317e778d963b8fe

**Comment by doomedraven** [comment]
All looks fine but you still have some problems, you need to investigate

**Comment by YESIHACK** [comment]
So after taking a break and coming back to the issue. I took a closer look at guest.py and noticed that it is getting the IP of the Results server. Is the the results server supposed to be guest VM IP?. I changed line 36 "self.ip = 'ip'" to "self.ip = '192.168.100.101'" to test it and looks to be communicating fine now. I think its importing the IP of the resultserver.

**Comment by doomedraven** [comment]
Resultserver is host io not vm ip, you can find it in cuckoo.conf or
hypervisor config

**Comment by YESIHACK** [comment]
Yaa The problem is that guest.py is importing "from lib.cuckoo.core.resultserver import ResultServer" and using HostIP when it should be using the guestip to connect. IP is declared variable in the resultserver.py

**Comment by doomedraven** [comment]
heh if that would be in that way how it would works till now? ;)

**Comment by YESIHACK** [comment]
Sorry I was wrong spacing was the problem. in the .conf file there was a space so 

IP=192.168.100.101 snapshot = Win7Snapshot

there was a space in the beginning of snapshot 

Rookie mistake. All is good.

**Comment by kevoreilly** [comment]
Awesome - glad it worked out and you now have a working instance :-)

**Comment by YESIHACK** [comment]
Yes, and thanks you all for your help. Hopfully this helps whoever has the same issue.

**Comment by doomedraven** [comment]
i think the best would be just add an strip on config load so it wouldn't care about spaces :)
