### ISSUE TITLE
Bugs after updating to the latest version

### ISSUE THREAD

**Issue by yevhenprotsenko** [ctxis/CAPE#422]
Hey guys, after updating to the latest version I have noticed 2 small bugs:

1) file `modules/signatures/network_doh.py` (additional space)
```python
            "89.233.43.71 ",
```
```
вер 13 08:14:34 cuckoo-nest python[9564]: 2019-09-13 08:14:34,050 [root] INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
вер 13 08:14:34 cuckoo-nest python[9564]: 2019-09-13 08:14:34,087 [root] INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
вер 13 08:14:34 cuckoo-nest python[9564]: Traceback (most recent call last):
вер 13 08:14:34 cuckoo-nest python[9564]:   File "cuckoo.py", line 138, in <module>
вер 13 08:14:34 cuckoo-nest python[9564]:     test=args.test)
вер 13 08:14:34 cuckoo-nest python[9564]:   File "cuckoo.py", line 60, in cuckoo_init
вер 13 08:14:34 cuckoo-nest python[9564]:     init_modules()
вер 13 08:14:34 cuckoo-nest python[9564]:   File "/dumps/cape-official/lib/cuckoo/core/startup.py", line 207, in init_modules
вер 13 08:14:34 cuckoo-nest python[9564]:     import_package(modules.signatures)
вер 13 08:14:34 cuckoo-nest python[9564]:   File "/dumps/cape-official/lib/cuckoo/core/plugins.py", line 49, in import_package
вер 13 08:14:34 cuckoo-nest python[9564]:     import_plugin(name)
вер 13 08:14:34 cuckoo-nest python[9564]:   File "/dumps/cape-official/lib/cuckoo/core/plugins.py", line 36, in import_plugin
вер 13 08:14:34 cuckoo-nest python[9564]:     module = __import__(name, globals(), locals(), ["dummy"], -1)
вер 13 08:14:34 cuckoo-nest python[9564]:   File "/dumps/cape-official/modules/signatures/network_doh.py", line 113
вер 13 08:14:34 cuckoo-nest python[9564]: SyntaxError: Non-ASCII character '\xc2' in file /dumps/cape-official/modules/signatures/network_doh.py on line 113, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for de
```
2)  file `utils/rooter.py` (unexpected indent)
```python
    dns_forward("-A", ipaddr, inetsim_ip, dns_port)
     run(settings.iptables, "-A", "OUTPUT", "--source", ipaddr, "-j", "DROP")
```

```
вер 13 08:26:07 cuckoo-nest systemd[1]: cape-rooter.service: Service hold-off time over, scheduling restart.
вер 13 08:26:07 cuckoo-nest systemd[1]: Stopped Cape rooter service.
вер 13 08:26:07 cuckoo-nest systemd[1]: Started Cape rooter service.
вер 13 08:26:07 cuckoo-nest python[24839]:   File "/dumps/cape-official/utils/rooter.py", line 158
вер 13 08:26:07 cuckoo-nest python[24839]:     run(settings.iptables, "-A", "OUTPUT", "--source", ipaddr, "-j", "DROP")
вер 13 08:26:07 cuckoo-nest python[24839]:     ^
вер 13 08:26:07 cuckoo-nest python[24839]: IndentationError: unexpected indent
```

**Comment by doomedraven** [comment]
@kevoreilly can you merge from your repo it was fixed there

**Comment by kevoreilly** [comment]
I've merged the latest updates - please let me know if there are any further issues.

**Comment by yevhenprotsenko** [comment]
Thanks!

**Comment by kevoreilly** [comment]
You're welcome :)
