### ISSUE TITLE
KeyError: (<weakref at 0x7fbf4a8f5d68; to 'function' at 0x7fbf43b9dd90 (go)>,)

### ISSUE THREAD

**Issue by helios4281** [ctxis/CAPE#475]
Cannot run cuckoo for the first time and having this issue: 

Exception ignored in: <bound method Database.__del__ of <lib.cuckoo.core.database.Database object at 0x7fbefcf22828>>
Traceback (most recent call last):
  File "/opt/CAPEv2/lib/cuckoo/core/database.py", line 447, in __del__
  File "/{redacted}/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2039, in dispose
  File "/{redacted}/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 251, in recreate
  File "<string>", line 2, in __init__
  File "/{redacted}/.local/lib/python3.6/site-packages/sqlalchemy/util/deprecations.py", line 128, in warned
  File "/{redacted}/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 221, in __init__
  File "/{redacted}/.local/lib/python3.6/site-packages/sqlalchemy/event/base.py", line 150, in _update
  File "/{redacted}/.local/lib/python3.6/site-packages/sqlalchemy/event/attr.py", line 392, in _update
  File "/{redacted}/.local/lib/python3.6/site-packages/sqlalchemy/event/registry.py", line 115, in _stored_in_collection_multi
KeyError: (<weakref at 0x7fbf4a8f5d68; to 'function' at 0x7fbf43b9dd90 (go)>,)

hopefully someone can help.

thanks.

**Comment by doomedraven** [comment]
1. wrong repo, read readme
2. there is cape2 on py3

**Comment by niuhuluzhihao** [comment]
hello ，how do you deal with it?I recently encountered this problem。

**Comment by Laurelea** [comment]
Having same issue
`KeyError: (<weakref at 0x7fdeb2e4c110; to 'function' at 0x7fdea1eaedd0 (on_connect)>,)`

**Comment by kevoreilly** [comment]
Guys! Did you read doomedraven's reply?

1. If you are actually using this repo/version on Python 2 then you are using a project that died 2 years ago and is totally unsupported.
2. If you are in fact using CAPEv2 on Python3 then you have created an issue in the wrong repository.
3. You have supplied almost no information whatsoever - because of issues lacking info like this we had to create an issue template - to force people to supply enough information for us to be able to help. So please use the template and supply a decent amount of background info on your setup.
