### ISSUE TITLE
Compression signature error

### ISSUE THREAD

**Issue by enzok** [ctxis/CAPE#76]
Getting the following error. Attaching sample.

'''
2018-08-16 15:58:47,279 [lib.cuckoo.core.plugins] ERROR: Failed to run signature "Compression":
Traceback (most recent call last):
  File "/opt/cuckoo/utils/../lib/cuckoo/core/plugins.py", line 414, in run
    result = sig.on_call(call, proc)
  File "/opt/cuckoo/utils/../modules/signatures/CAPE.py", line 69, in on_call
    machine_probe = struct.unpack("<H", buf[offset:offset+2])[0]
error: unpack requires a string argument of length 2
'''

sample md5: 

9270ac1e013a3b33c44666a66795d0c0

**Comment by kevoreilly** [comment]
Just pushed a fix for this - thanks for the heads up.
